# fish/abbr.fish

abbr -a .. 'cd ..'
abbr -a ... 'cd ../..'
abbr -a .... 'cd ../../..'

abbr -a ga 'git add'
abbr -a gaa 'git add --all'
abbr -a gc 'git commit'
abbr -a gca 'git commit --amend'
abbr -a gcm 'git commit -m'
abbr -a gcn 'git commit -n'
abbr -a gcp 'git cherry-pick'
abbr -a gb 'git branch'
abbr -a gbd 'git branch -d'
abbr -a gbr 'git branch -r'
abbr -a gd 'git diff'
abbr -a gd 'git diff'
abbr -a gds 'git diff --staged'
abbr -a gf 'git fetch'
abbr -a gl 'git log -n 10'
abbr -a glo 'git log --oneline --graph --decorate'
abbr -a gp 'git push'
abbr -a gpf 'git push --force-with-lease'
abbr -a gpu 'git push -u origin HEAD'
abbr -a gpr 'git pull --rebase'
abbr -a gra 'git rebase --abort'
abbr -a grc 'git rebase --continue'
abbr -a grom 'git rebase origin/main'
abbr -a gromi 'git rebase origin/main -i'
abbr -a gsh 'git show'
abbr -a gst 'git status'
abbr -a gsw 'git switch'
abbr -a gswc 'git switch -c'

abbr -a d 'docker'
abbr -a db 'docker build .'
abbr -a dr 'docker run -it --rm'
abbr -a dps 'docker ps'
abbr -a dpsa 'docker ps -a'
abbr -a dimg 'docker images'
abbr -a drm 'docker rm'
abbr -a drmi 'docker rmi'
abbr -a dex 'docker exec -it'
abbr -a dlogs 'docker logs -f'
abbr -a dstop 'docker stop'
abbr -a dprune 'docker system prune -af'

abbr -a dc 'docker compose'
abbr -a dcu 'docker compose up -d'
abbr -a dcb 'docker compose build'
abbr -a dcd 'docker compose down'
abbr -a dcr 'docker compose run'
abbr -a dcl 'docker compose logs -f'
